@ stdcall vkAcquireNextImageKHR(ptr int64 int64 int64 int64 ptr)
@ stdcall vkAllocateCommandBuffers(ptr ptr ptr)
@ stdcall vkAllocateDescriptorSets(ptr ptr ptr)
@ stdcall vkAllocateMemory(ptr ptr ptr ptr)
@ stdcall vkBeginCommandBuffer(ptr ptr)
@ stdcall vkBindBufferMemory(ptr int64 int64 int64)
@ stdcall vkBindImageMemory(ptr int64 int64 int64)
@ stdcall vkCmdBeginQuery(ptr int64 long long)
@ stdcall vkCmdBeginRenderPass(ptr ptr long)
@ stdcall vkCmdBindDescriptorSets(ptr long int64 long long ptr long ptr)
@ stdcall vkCmdBindIndexBuffer(ptr int64 int64 long)
@ stdcall vkCmdBindPipeline(ptr long int64)
@ stdcall vkCmdBindVertexBuffers(ptr long long ptr ptr)
@ stdcall vkCmdBlitImage(ptr int64 long int64 long long ptr long)
@ stdcall vkCmdClearAttachments(ptr long ptr long ptr)
@ stdcall vkCmdClearColorImage(ptr int64 long ptr long ptr)
@ stdcall vkCmdClearDepthStencilImage(ptr int64 long ptr long ptr)
@ stdcall vkCmdCopyBuffer(ptr int64 int64 long ptr)
@ stdcall vkCmdCopyBufferToImage(ptr int64 int64 long long ptr)
@ stdcall vkCmdCopyImage(ptr int64 long int64 long long ptr)
@ stdcall vkCmdCopyImageToBuffer(ptr int64 long int64 long ptr)
@ stdcall vkCmdCopyQueryPoolResults(ptr int64 long long int64 int64 int64 long)
@ stdcall vkCmdDispatch(ptr long long long)
@ stdcall vkCmdDispatchIndirect(ptr int64 int64)
@ stdcall vkCmdDraw(ptr long long long long)
@ stdcall vkCmdDrawIndexed(ptr long long long long long)
@ stdcall vkCmdDrawIndexedIndirect(ptr int64 int64 long long)
@ stdcall vkCmdDrawIndirect(ptr int64 int64 long long)
@ stdcall vkCmdEndQuery(ptr int64 long)
@ stdcall vkCmdEndRenderPass(ptr)
@ stdcall vkCmdExecuteCommands(ptr long ptr)
@ stdcall vkCmdFillBuffer(ptr int64 int64 int64 long)
@ stdcall vkCmdNextSubpass(ptr long)
@ stdcall vkCmdPipelineBarrier(ptr long long long long ptr long ptr long ptr)
@ stdcall vkCmdPushConstants(ptr int64 long long long ptr)
@ stdcall vkCmdResetEvent(ptr int64 long)
@ stdcall vkCmdResetQueryPool(ptr int64 long long)
@ stdcall vkCmdResolveImage(ptr int64 long int64 long long ptr)
@ stdcall vkCmdSetBlendConstants(ptr ptr)
@ stdcall vkCmdSetDepthBias(ptr float float float)
@ stdcall vkCmdSetDepthBounds(ptr float float)
@ stdcall vkCmdSetEvent(ptr int64 long)
@ stdcall vkCmdSetLineWidth(ptr float)
@ stdcall vkCmdSetScissor(ptr long long ptr)
@ stdcall vkCmdSetStencilCompareMask(ptr long long)
@ stdcall vkCmdSetStencilReference(ptr long long)
@ stdcall vkCmdSetStencilWriteMask(ptr long long)
@ stdcall vkCmdSetViewport(ptr long long ptr)
@ stdcall vkCmdUpdateBuffer(ptr int64 int64 int64 ptr)
@ stdcall vkCmdWaitEvents(ptr long ptr long long long ptr long ptr long ptr)
@ stdcall vkCmdWriteTimestamp(ptr long int64 long)
@ stdcall vkCreateBuffer(ptr ptr ptr ptr)
@ stdcall vkCreateBufferView(ptr ptr ptr ptr)
@ stdcall vkCreateCommandPool(ptr ptr ptr ptr)
@ stdcall vkCreateComputePipelines(ptr int64 long ptr ptr ptr)
@ stdcall vkCreateDebugReportCallbackEXT(ptr ptr ptr ptr)
@ stdcall vkCreateDescriptorPool(ptr ptr ptr ptr)
@ stdcall vkCreateDescriptorSetLayout(ptr ptr ptr ptr)
@ stdcall vkCreateDevice(ptr ptr ptr ptr)
@ stdcall vkCreateDisplayModeKHR(ptr int64 ptr ptr ptr)
@ stdcall vkCreateDisplayPlaneSurfaceKHR(ptr ptr ptr ptr)
@ stdcall vkCreateEvent(ptr ptr ptr ptr)
@ stdcall vkCreateFence(ptr ptr ptr ptr)
@ stdcall vkCreateFramebuffer(ptr ptr ptr ptr)
@ stdcall vkCreateGraphicsPipelines(ptr int64 long ptr ptr ptr)
@ stdcall vkCreateImage(ptr ptr ptr ptr)
@ stdcall vkCreateImageView(ptr ptr ptr ptr)
@ stdcall vkCreateInstance(ptr ptr ptr)
@ stdcall vkCreatePipelineCache(ptr ptr ptr ptr)
@ stdcall vkCreatePipelineLayout(ptr ptr ptr ptr)
@ stdcall vkCreateQueryPool(ptr ptr ptr ptr)
@ stdcall vkCreateRenderPass(ptr ptr ptr ptr)
@ stdcall vkCreateSampler(ptr ptr ptr ptr)
@ stdcall vkCreateSemaphore(ptr ptr ptr ptr)
@ stdcall vkCreateShaderModule(ptr ptr ptr ptr)
@ stdcall vkCreateSharedSwapchainsKHR(ptr long ptr ptr ptr)
@ stdcall vkCreateSwapchainKHR(ptr ptr ptr ptr)
@ stdcall vkCreateWin32SurfaceKHR(ptr ptr ptr ptr)
@ stdcall vkDebugReportMessageEXT(ptr long long int64 long long str str)
@ stdcall vkDestroyBuffer(ptr int64 ptr)
@ stdcall vkDestroyBufferView(ptr int64 ptr)
@ stdcall vkDestroyCommandPool(ptr int64 ptr)
@ stdcall vkDestroyDebugReportCallbackEXT(ptr int64 ptr)
@ stdcall vkDestroyDescriptorPool(ptr int64 ptr)
@ stdcall vkDestroyDescriptorSetLayout(ptr int64 ptr)
@ stdcall vkDestroyDevice(ptr ptr)
@ stdcall vkDestroyEvent(ptr int64 ptr)
@ stdcall vkDestroyFence(ptr int64 ptr)
@ stdcall vkDestroyFramebuffer(ptr int64 ptr)
@ stdcall vkDestroyImage(ptr int64 ptr)
@ stdcall vkDestroyImageView(ptr int64 ptr)
@ stdcall vkDestroyInstance(ptr ptr)
@ stdcall vkDestroyPipeline(ptr int64 ptr)
@ stdcall vkDestroyPipelineCache(ptr int64 ptr)
@ stdcall vkDestroyPipelineLayout(ptr int64 ptr)
@ stdcall vkDestroyQueryPool(ptr int64 ptr)
@ stdcall vkDestroyRenderPass(ptr int64 ptr)
@ stdcall vkDestroySampler(ptr int64 ptr)
@ stdcall vkDestroySemaphore(ptr int64 ptr)
@ stdcall vkDestroyShaderModule(ptr int64 ptr)
@ stdcall vkDestroySurfaceKHR(ptr int64 ptr)
@ stdcall vkDestroySwapchainKHR(ptr int64 ptr)
@ stdcall vkDeviceWaitIdle(ptr)
@ stdcall vkEndCommandBuffer(ptr)
@ stdcall vkEnumerateDeviceExtensionProperties(ptr str ptr ptr)
@ stdcall vkEnumerateDeviceLayerProperties(ptr ptr ptr)
@ stdcall vkEnumerateInstanceExtensionProperties(str ptr ptr)
@ stdcall vkEnumerateInstanceLayerProperties(ptr ptr)
@ stdcall vkEnumeratePhysicalDevices(ptr ptr ptr)
@ stdcall vkFlushMappedMemoryRanges(ptr long ptr)
@ stdcall vkFreeCommandBuffers(ptr int64 long ptr)
@ stdcall vkFreeDescriptorSets(ptr int64 long ptr)
@ stdcall vkFreeMemory(ptr int64 ptr)
@ stdcall vkGetBufferMemoryRequirements(ptr int64 ptr)
@ stdcall vkGetDeviceMemoryCommitment(ptr int64 ptr)
@ stdcall vkGetDeviceProcAddr(ptr str)
@ stdcall vkGetDeviceQueue(ptr long long ptr)
@ stdcall vkGetDisplayModePropertiesKHR(ptr int64 ptr ptr)
@ stdcall vkGetDisplayPlaneCapabilitiesKHR(ptr int64 long ptr)
@ stdcall vkGetDisplayPlaneSupportedDisplaysKHR(ptr long ptr ptr)
@ stdcall vkGetEventStatus(ptr int64)
@ stdcall vkGetFenceStatus(ptr int64)
@ stdcall vkGetImageMemoryRequirements(ptr int64 ptr)
@ stdcall vkGetImageSparseMemoryRequirements(ptr int64 ptr ptr)
@ stdcall vkGetImageSubresourceLayout(ptr int64 ptr ptr)
@ stdcall vkGetInstanceProcAddr(ptr str)
@ stdcall vkGetPhysicalDeviceDisplayPlanePropertiesKHR(ptr ptr ptr)
@ stdcall vkGetPhysicalDeviceDisplayPropertiesKHR(ptr ptr ptr)
@ stdcall vkGetPhysicalDeviceFeatures(ptr ptr)
@ stdcall vkGetPhysicalDeviceFormatProperties(ptr long ptr)
@ stdcall vkGetPhysicalDeviceImageFormatProperties(ptr long long long long long ptr)
@ stdcall vkGetPhysicalDeviceMemoryProperties(ptr ptr)
@ stdcall vkGetPhysicalDeviceProperties(ptr ptr)
@ stdcall vkGetPhysicalDeviceQueueFamilyProperties(ptr ptr ptr)
@ stdcall vkGetPhysicalDeviceSparseImageFormatProperties(ptr long long long long long ptr ptr)
@ stdcall vkGetPhysicalDeviceSurfaceCapabilitiesKHR(ptr int64 ptr)
@ stdcall vkGetPhysicalDeviceSurfaceFormatsKHR(ptr int64 ptr ptr)
@ stdcall vkGetPhysicalDeviceSurfacePresentModesKHR(ptr int64 ptr ptr)
@ stdcall vkGetPhysicalDeviceSurfaceSupportKHR(ptr long int64 ptr)
@ stdcall vkGetPhysicalDeviceWin32PresentationSupportKHR(ptr long)
@ stdcall vkGetPipelineCacheData(ptr int64 ptr ptr)
@ stdcall vkGetQueryPoolResults(ptr int64 long long long ptr int64 long)
@ stdcall vkGetRenderAreaGranularity(ptr int64 ptr)
@ stdcall vkGetSwapchainImagesKHR(ptr int64 ptr ptr)
@ stdcall vkInvalidateMappedMemoryRanges(ptr long ptr)
@ stdcall vkMapMemory(ptr int64 int64 int64 long ptr)
@ stdcall vkMergePipelineCaches(ptr int64 long ptr)
@ stdcall vkQueueBindSparse(ptr long ptr int64)
@ stdcall vkQueuePresentKHR(ptr ptr)
@ stdcall vkQueueSubmit(ptr long ptr int64)
@ stdcall vkQueueWaitIdle(ptr)
@ stdcall vkResetCommandBuffer(ptr long)
@ stdcall vkResetCommandPool(ptr int64 long)
@ stdcall vkResetDescriptorPool(ptr int64 long)
@ stdcall vkResetEvent(ptr int64)
@ stdcall vkResetFences(ptr long ptr)
@ stdcall vkSetEvent(ptr int64)
@ stdcall vkUnmapMemory(ptr int64)
@ stdcall vkUpdateDescriptorSets(ptr long ptr long ptr)
@ stdcall vkWaitForFences(ptr long ptr long int64)
