@ stub EdpContainerizeFile
@ stub EdpCredentialCreate
@ stub EdpCredentialDelete
@ stub EdpCredentialExists
@ stub EdpCredentialQuery
@ stub EdpDecontainerizeFile
@ stub EdpDplPolicyEnabledForUser
@ stub EdpDplUpgradePinInfo
@ stub EdpDplUpgradeVerifyUser
@ stub EdpDplUserCredentialsSet
@ stub EdpDplUserUnlockComplete
@ stub EdpDplUserUnlockStart
@ stub EdpFree
@ stub EdpGetContainerIdentity
@ stub EdpGetCredServiceState
@ stub EdpQueryCredServiceInfo
@ stub EdpQueryDplEnforcedPolicyOwnerIds
@ stub EdpQueryRevokedPolicyOwnerIds
@ stub EdpRmsClearKeys
@ stub EdpSetCredServiceInfo
@ stub EfsClientCloseFileRaw
@ stub EfsClientDecryptFile
@ stub EfsClientDuplicateEncryptionInfo
@ stub EfsClientEncryptFileEx
@ stub EfsClientFileEncryptionStatus
@ stub EfsClientFreeProtectorList
@ stub EfsClientGetEncryptedFileVersion
@ stub EfsClientOpenFileRaw
@ stub EfsClientQueryProtectors
@ stub EfsClientReadFileRaw
@ stub EfsClientWriteFileRaw
@ stub EfsClientWriteFileWithHeaderRaw
@ stub EfsUtilGetCurrentKey
@ stub FeClientInitialize
@ stub GetLockSessionUnwrappedKey
@ stub GetLockSessionWrappedKey
