@ stub PathAllocCanonicalize
@ stub PathAllocCombine
@ stub PathCchAddBackslash
@ stub PathCchAddBackslashEx
@ stub PathCchAddExtension
@ stub PathCchAppend
@ stub PathCchAppendEx
@ stub PathCchCanonicalize
@ stub PathCchCanonicalizeEx
@ stub PathCchCombine
@ stdcall PathCchCombineEx(ptr long ptr ptr long) kernelbase.PathCchCombineEx
@ stub PathCchFindExtension
@ stub PathCchIsRoot
@ stub PathCchRemoveBackslash
@ stub PathCchRemoveBackslashEx
@ stub PathCchRemoveExtension
@ stub PathCchRemoveFileSpec
@ stub PathCchRenameExtension
@ stub PathCchSkipRoot
@ stub PathCchStripPrefix
@ stub PathCchStripToRoot
@ stub PathIsUNCEx
