@ stub TdrCompleteRecoveryContext
@ stub TdrCreateRecoveryContext
@ stub TdrIsRecoveryRequired
@ stub TdrIsTimeoutForcedFlip
@ stub TdrResetFromTimeout
@ stub g_TdrConfig
@ stub g_TdrForceTimeout
@ stub DpSynchronizeExecution
@ stub DpiGetDriverVersion
@ stub DpiGetDxgAdapter
@ stub DpiGetSchedulerCallbackState
@ stub DpiSetSchedulerCallbackState
@ stub DxgCoreInterface
@ stub DxgkSqmAddToStream
@ stub DxgkSqmCommonGeneric
@ stub DxgkSqmCreateDwordStreamEntry
@ stub DxgkSqmCreateStringStreamEntry
@ stub DxgkSqmGenericDword
@ stub DxgkSqmGenericDword64
@ stub TraceDxgkBlockThread
@ stub TraceDxgkContext
@ stub TraceDxgkDevice
@ stub TraceDxgkFunctionProfiler
@ stub TraceDxgkPerformanceWarning
@ stub TraceDxgkPresentHistory
@ stub g_loggerInfo
